/*
 * theme.h — palette, fonts, and helpers for reusable LVGL card styles.
 *
 * Lightweight theme primitives shared by the main pages and idle screen.
 */
#pragma once

#include "app_config.h"
#include "lvgl.h"
#include "weather_icons.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dark surface palette. */
#define THEME_DEFAULT_BG_HEX       0x05070D
#define THEME_DEFAULT_SURFACE_HEX  0x111625
#define THEME_DEFAULT_CARD_HEX     0x171D31
#define THEME_DEFAULT_BORDER_HEX   0x303A59
#define THEME_DEFAULT_PRIMARY_HEX  0x1E86FF
#define THEME_DEFAULT_ACCENT_HEX   0xFF4B00

#define THEME_BG_COLOR        theme_bg_color()
#define THEME_SURFACE_COLOR   theme_surface_color()
#define THEME_CARD_COLOR      theme_card_color()
#define THEME_BORDER_COLOR    theme_border_color()
#define THEME_PRIMARY_COLOR   theme_primary_color()
#define THEME_ACCENT_COLOR    theme_accent_color()
#define THEME_TEXT_PRIMARY    lv_color_hex(0xFFFFFF)
#define THEME_TEXT_SECONDARY  lv_color_hex(0xB8C1E6)
#define THEME_TEXT_MUTED      lv_color_hex(0x7883AB)
#define THEME_ERROR_COLOR     lv_color_hex(0xEF5350)

/* Fonts (must be enabled in sdkconfig). */
#define THEME_FONT_HERO       (&lv_font_montserrat_48)
#define THEME_FONT_XLARGE     (&lv_font_montserrat_32)
#define THEME_FONT_LARGE      (&lv_font_montserrat_28)
#define THEME_FONT_DISPLAY    (&lv_font_montserrat_26)
#define THEME_FONT_TITLE      (&lv_font_montserrat_24)
#define THEME_FONT_BODY       (&lv_font_montserrat_18)
#define THEME_FONT_LABEL      (&lv_font_montserrat_16)
#define THEME_FONT_SMALL      (&lv_font_montserrat_14)

/* Weather glyph and numeric fonts generated by scripts/gen_weather_font.sh. */
#define THEME_FONT_WX_SMALL   (&weather_icons_28)
#define THEME_FONT_WX_MEDIUM  (&weather_icons_60)
#define THEME_FONT_WX_LARGE   (&weather_icons_96)
#define THEME_FONT_WX_HERO    (&weather_icons_120)
#define THEME_FONT_WX_TEMP    (&weather_digits_72)
#define THEME_FONT_WX_HERO_NUM (&weather_digits_150)
#define THEME_FONT_WX_TIME    (&weather_digits_150)
#define THEME_FONT_WX_SECONDS (&weather_digits_96)

/* Apply theme defaults (background, default text color/font) to a screen. */
void theme_apply_screen(lv_obj_t *scr);

lv_color_t theme_bg_color(void);
lv_color_t theme_surface_color(void);
lv_color_t theme_card_color(void);
lv_color_t theme_border_color(void);
lv_color_t theme_primary_color(void);
lv_color_t theme_accent_color(void);
void theme_apply_config(const app_theme_config_t *cfg);
void theme_recolor_tree(lv_obj_t *root);

/* Create a rounded surface "card" under parent. Caller sets size+pos.
 * Card has: surface bg, 1 px border, 18 px radius, 16 px inner padding. */
lv_obj_t *theme_card_create(lv_obj_t *parent);

/* Runtime glass opacity, controlled by Settings > Theme. */
void theme_set_surface_opacity_pct(uint8_t pct);
uint8_t theme_surface_opacity_pct(void);
lv_opa_t theme_surface_opa(void);
void theme_style_glass_panel(lv_obj_t *obj, lv_coord_t radius);
void theme_apply_surface_opacity(lv_obj_t *root);

/* Create a vertical flex column under parent (gap, padding) used as the
 * top-level layout of a tab/screen. */
lv_obj_t *theme_column_create(lv_obj_t *parent);

/* Create a primary header label (title) and an optional caption beneath.
 * Returns the title label; caption may be NULL. */
lv_obj_t *theme_header_create(lv_obj_t *parent, const char *title, const char *caption);

/* Create a pill-shaped status badge with the given text + bg color. */
lv_obj_t *theme_badge_create(lv_obj_t *parent, const char *text, lv_color_t bg);

/* Create a section header label (small, uppercase, muted) used to group
 * settings rows. Adds top padding so it visually separates from the
 * previous group. */
lv_obj_t *theme_section_header(lv_obj_t *parent, const char *text);

/* Create a flat row container with optional gap. */
lv_obj_t *theme_row_create(lv_obj_t *parent, lv_coord_t gap);

/* Create a flat column container with optional gap. */
lv_obj_t *theme_col_create(lv_obj_t *parent, lv_coord_t gap);

/* Style a button as the primary (filled) variant. */
void theme_btn_style_primary(lv_obj_t *btn);
/* Style a button as the secondary (outlined) variant. */
void theme_btn_style_secondary(lv_obj_t *btn);

#ifdef __cplusplus
}
#endif
