/* ---------------------------------------------------------------------------
 * ui_icons.h - generated shared LVGL icon font for UI chrome (nav bar,
 * Settings menu, status bar).
 *
 * Generated by scripts/gen_ui_icons_font.sh from Phosphor Icons (MIT). The
 * UTF-8 string literals encode Phosphor Private-Use-Area code-points; rendered
 * with ui_icons_24/28/32 they recolor with LVGL like any other glyph.
 * --------------------------------------------------------------------------- */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(ui_icons_24);
LV_FONT_DECLARE(ui_icons_28);
LV_FONT_DECLARE(ui_icons_32);
LV_FONT_DECLARE(ui_icons_bold_30);

#define UI_ICON_LIGHTS      "\xEE\x8B\x9C"  /* U+E2DC ph-lightbulb */
#define UI_ICON_WEATHER     "\xEE\x95\x80"  /* U+E540 ph-cloud-sun */
#define UI_ICON_WEATHER_OFF "\xEE\x86\xB6"  /* U+E1B6 ph-cloud-slash */
#define UI_ICON_TIMER       "\xEE\x8A\xB2"  /* U+E2B2 ph-hourglass */
#define UI_ICON_SETTINGS    "\xEE\x89\xB0"  /* U+E270 ph-gear */
#define UI_ICON_WIFI        "\xEE\x93\xAA"  /* U+E4EA ph-wifi-high */
#define UI_ICON_WIFI_LOW    "\xEE\x93\xAC"  /* U+E4EC ph-wifi-low */
#define UI_ICON_WIFI_OFF    "\xEE\x93\xB2"  /* U+E4F2 ph-wifi-slash */
#define UI_ICON_DISPLAY     "\xEE\x8C\xAE"  /* U+E32E ph-monitor */
#define UI_ICON_IDLE        "\xEE\x8C\xB0"  /* U+E330 ph-moon */
#define UI_ICON_THEME       "\xEE\x8B\x8A"  /* U+E2CA ph-image */
#define UI_ICON_SD          "\xEE\x89\x88"  /* U+E248 ph-floppy-disk */
#define UI_ICON_WLED        "\xEE\x8B\x9E"  /* U+E2DE ph-lightning */
#define UI_ICON_WLED_OFF    "\xEE\x8B\xA0"  /* U+E2E0 ph-lightning-slash */
#define UI_ICON_LINK        "\xEE\x8B\xA2"  /* U+E2E2 ph-link */
#define UI_ICON_LINK_OFF    "\xEE\x8B\xA4"  /* U+E2E4 ph-link-break */
#define UI_ICON_AUDIO       "\xEE\x8C\xA6"  /* U+E326 ph-microphone */
#define UI_ICON_AUDIO_OFF   "\xEE\x8C\xA8"  /* U+E328 ph-microphone-slash */
#define UI_ICON_INFO        "\xEE\x8B\x8E"  /* U+E2CE ph-info */
#define UI_ICON_SUN         "\xEE\x91\xB2"  /* U+E472 ph-sun */
#define UI_ICON_SUN_DIM     "\xEE\x91\xB4"  /* U+E474 ph-sun-dim */

#ifdef __cplusplus
}
#endif
