/* ---------------------------------------------------------------------------
 * weather_icons.h - generated LVGL weather icon and numeric font declarations.
 *
 * Generated by scripts/gen_weather_font.sh. UTF-8 string literals below encode
 * the Private-Use-Area code-points from Erik Flowers Weather Icons.
 *
 * lmarzen/esp32-weather-epd gets its reference look from fixed-size bitmaps
 * under platformio/lib/esp32-weather-epd-assets/icons and maps OWM conditions
 * through display_utils.cpp:getConditionsBitmap(). This firmware uses the same
 * icon vocabulary as native-size LVGL fonts instead of copying GPL bitmap
 * headers into the project.
 * --------------------------------------------------------------------------- */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(weather_icons_28);
LV_FONT_DECLARE(weather_icons_60);
LV_FONT_DECLARE(weather_icons_96);
LV_FONT_DECLARE(weather_icons_120);
LV_FONT_DECLARE(weather_digits_72);
LV_FONT_DECLARE(weather_digits_96);
LV_FONT_DECLARE(weather_digits_150);

/* Day variants */
#define WI_DAY_SUNNY            "\xEF\x80\x8D"  /* U+F00D wi-day-sunny */
#define WI_DAY_CLOUDY           "\xEF\x80\x82"  /* U+F002 wi-day-cloudy */
#define WI_DAY_RAIN             "\xEF\x80\x88"  /* U+F008 wi-day-rain */
#define WI_DAY_SNOW             "\xEF\x80\x8A"  /* U+F00A wi-day-snow */
#define WI_DAY_THUNDER          "\xEF\x80\x90"  /* U+F010 wi-day-thunderstorm */
#define WI_DAY_FOG              "\xEF\x80\x83"  /* U+F003 wi-day-fog */

/* Night variants */
#define WI_NIGHT_CLEAR          "\xEF\x80\xAE"  /* U+F02E wi-night-clear */
#define WI_NIGHT_CLOUDY         "\xEF\x82\x86"  /* U+F086 wi-night-alt-cloudy */
#define WI_NIGHT_RAIN           "\xEF\x80\xA8"  /* U+F028 wi-night-alt-rain */
#define WI_NIGHT_SNOW           "\xEF\x80\xAA"  /* U+F02A wi-night-alt-snow */
#define WI_NIGHT_THUNDER        "\xEF\x80\xAD"  /* U+F02D wi-night-alt-thunderstorm */
#define WI_NIGHT_FOG            "\xEF\x81\x8A"  /* U+F04A wi-night-fog */

/* Generic */
#define WI_CLOUD                "\xEF\x81\x81"  /* U+F041 wi-cloud */
#define WI_RAIN                 "\xEF\x80\x99"  /* U+F019 wi-rain */
#define WI_SNOW                 "\xEF\x80\x9B"  /* U+F01B wi-snow */
#define WI_TORNADO              "\xEF\x81\x96"  /* U+F056 wi-tornado */
#define WI_THUNDER              "\xEF\x80\x9E"  /* U+F01E wi-thunderstorm */
#define WI_FOG                  "\xEF\x80\x94"  /* U+F014 wi-fog */
#define WI_WINDY                "\xEF\x80\xA1"  /* U+F021 wi-windy */
#define WI_STRONG_WIND          "\xEF\x81\x90"  /* U+F050 wi-strong-wind */
#define WI_RAINDROPS            "\xEF\x81\x8E"  /* U+F04E wi-raindrops */
#define WI_CLOUD_UP             "\xEF\x81\x80"  /* U+F040 wi-cloud-up (gust) */

/* Metrics / indicators */
#define WI_THERMOMETER          "\xEF\x81\x95"  /* U+F055 wi-thermometer */
#define WI_HUMIDITY             "\xEF\x81\xBA"  /* U+F07A wi-humidity */
#define WI_BAROMETER            "\xEF\x81\xB9"  /* U+F079 wi-barometer */
#define WI_SUNRISE              "\xEF\x81\x91"  /* U+F051 wi-sunrise */
#define WI_SUNSET               "\xEF\x81\x92"  /* U+F052 wi-sunset */
#define WI_WIND_DIRECTION       "\xEF\x82\xB1"  /* U+F0B1 wi-wind-direction */
#define WI_HOT                  "\xEF\x81\xB2"  /* U+F072 wi-hot */
#define WI_EYE                  "\xEF\x81\x87"  /* U+F047 wi-horizon (visibility) */
#define WI_NA                   "\xEF\x81\xBB"  /* U+F07B wi-na (unknown) */
#define WI_SMALL_CRAFT          "\xEF\x83\x8C"  /* U+F0CC wi-small-craft-advisory */

#ifdef __cplusplus
}
#endif
