/* ---------------------------------------------------------------------------
 * weather_icons.h - generated LVGL weather icon and numeric font declarations.
 *
 * Generated by scripts/gen_weather_font.sh. UTF-8 string literals below encode
 * the Private-Use-Area code-points from Erik Flowers Weather Icons.
 *
 * lmarzen/esp32-weather-epd gets its reference look from fixed-size bitmaps
 * under platformio/lib/esp32-weather-epd-assets/icons and maps OWM conditions
 * through display_utils.cpp:getConditionsBitmap(). This firmware uses the same
 * icon vocabulary as native-size LVGL fonts instead of copying GPL bitmap
 * headers into the project.
 * --------------------------------------------------------------------------- */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(weather_icons_28);
LV_FONT_DECLARE(weather_icons_60);
LV_FONT_DECLARE(weather_icons_96);
LV_FONT_DECLARE(weather_icons_120);
LV_FONT_DECLARE(weather_digits_72);
LV_FONT_DECLARE(weather_digits_96);
LV_FONT_DECLARE(weather_digits_150);

/* Day variants */
#define WI_DAY_SUNNY            "\xEF\x80\x8D"  /* U+F00D wi-day-sunny */
#define WI_DAY_CLOUDY           "\xEF\x80\x82"  /* U+F002 wi-day-cloudy */
#define WI_DAY_RAIN             "\xEF\x80\x88"  /* U+F008 wi-day-rain */
#define WI_DAY_SNOW             "\xEF\x80\x8A"  /* U+F00A wi-day-snow */
#define WI_DAY_THUNDER          "\xEF\x80\x90"  /* U+F010 wi-day-thunderstorm */
#define WI_DAY_FOG              "\xEF\x80\x83"  /* U+F003 wi-day-fog */

/* Night variants */
#define WI_NIGHT_CLEAR          "\xEF\x80\xAE"  /* U+F02E wi-night-clear */
#define WI_NIGHT_CLOUDY         "\xEF\x82\x86"  /* U+F086 wi-night-alt-cloudy */
#define WI_NIGHT_RAIN           "\xEF\x80\xA8"  /* U+F028 wi-night-alt-rain */
#define WI_NIGHT_SNOW           "\xEF\x80\xAA"  /* U+F02A wi-night-alt-snow */
#define WI_NIGHT_THUNDER        "\xEF\x80\xAD"  /* U+F02D wi-night-alt-thunderstorm */
#define WI_NIGHT_FOG            "\xEF\x81\x8A"  /* U+F04A wi-night-fog */

/* Moon phases */
#define WI_MOON_NEW             "\xEF\x82\x95"  /* U+F095 wi-moon-new */
#define WI_MOON_WAXING_CRESCENT_1 "\xEF\x82\x96"  /* U+F096 wi-moon-waxing-crescent-1 */
#define WI_MOON_WAXING_CRESCENT_2 "\xEF\x82\x97"  /* U+F097 wi-moon-waxing-crescent-2 */
#define WI_MOON_WAXING_CRESCENT_3 "\xEF\x82\x98"  /* U+F098 wi-moon-waxing-crescent-3 */
#define WI_MOON_WAXING_CRESCENT_4 "\xEF\x82\x99"  /* U+F099 wi-moon-waxing-crescent-4 */
#define WI_MOON_WAXING_CRESCENT_5 "\xEF\x82\x9A"  /* U+F09A wi-moon-waxing-crescent-5 */
#define WI_MOON_WAXING_CRESCENT_6 "\xEF\x82\x9B"  /* U+F09B wi-moon-waxing-crescent-6 */
#define WI_MOON_FIRST_QUARTER   "\xEF\x82\x9C"  /* U+F09C wi-moon-first-quarter */
#define WI_MOON_WAXING_GIBBOUS_1 "\xEF\x82\x9D"  /* U+F09D wi-moon-waxing-gibbous-1 */
#define WI_MOON_WAXING_GIBBOUS_2 "\xEF\x82\x9E"  /* U+F09E wi-moon-waxing-gibbous-2 */
#define WI_MOON_WAXING_GIBBOUS_3 "\xEF\x82\x9F"  /* U+F09F wi-moon-waxing-gibbous-3 */
#define WI_MOON_WAXING_GIBBOUS_4 "\xEF\x82\xA0"  /* U+F0A0 wi-moon-waxing-gibbous-4 */
#define WI_MOON_WAXING_GIBBOUS_5 "\xEF\x82\xA1"  /* U+F0A1 wi-moon-waxing-gibbous-5 */
#define WI_MOON_WAXING_GIBBOUS_6 "\xEF\x82\xA2"  /* U+F0A2 wi-moon-waxing-gibbous-6 */
#define WI_MOON_FULL            "\xEF\x82\xA3"  /* U+F0A3 wi-moon-full */
#define WI_MOON_WANING_GIBBOUS_1 "\xEF\x82\xA4"  /* U+F0A4 wi-moon-waning-gibbous-1 */
#define WI_MOON_WANING_GIBBOUS_2 "\xEF\x82\xA5"  /* U+F0A5 wi-moon-waning-gibbous-2 */
#define WI_MOON_WANING_GIBBOUS_3 "\xEF\x82\xA6"  /* U+F0A6 wi-moon-waning-gibbous-3 */
#define WI_MOON_WANING_GIBBOUS_4 "\xEF\x82\xA7"  /* U+F0A7 wi-moon-waning-gibbous-4 */
#define WI_MOON_WANING_GIBBOUS_5 "\xEF\x82\xA8"  /* U+F0A8 wi-moon-waning-gibbous-5 */
#define WI_MOON_WANING_GIBBOUS_6 "\xEF\x82\xA9"  /* U+F0A9 wi-moon-waning-gibbous-6 */
#define WI_MOON_THIRD_QUARTER   "\xEF\x82\xAA"  /* U+F0AA wi-moon-third-quarter */
#define WI_MOON_WANING_CRESCENT_1 "\xEF\x82\xAB"  /* U+F0AB wi-moon-waning-crescent-1 */
#define WI_MOON_WANING_CRESCENT_2 "\xEF\x82\xAC"  /* U+F0AC wi-moon-waning-crescent-2 */
#define WI_MOON_WANING_CRESCENT_3 "\xEF\x82\xAD"  /* U+F0AD wi-moon-waning-crescent-3 */
#define WI_MOON_WANING_CRESCENT_4 "\xEF\x82\xAE"  /* U+F0AE wi-moon-waning-crescent-4 */
#define WI_MOON_WANING_CRESCENT_5 "\xEF\x82\xAF"  /* U+F0AF wi-moon-waning-crescent-5 */
#define WI_MOON_WANING_CRESCENT_6 "\xEF\x82\xB0"  /* U+F0B0 wi-moon-waning-crescent-6 */

/* Generic */
#define WI_CLOUD                "\xEF\x81\x81"  /* U+F041 wi-cloud */
#define WI_RAIN                 "\xEF\x80\x99"  /* U+F019 wi-rain */
#define WI_SNOW                 "\xEF\x80\x9B"  /* U+F01B wi-snow */
#define WI_TORNADO              "\xEF\x81\x96"  /* U+F056 wi-tornado */
#define WI_THUNDER              "\xEF\x80\x9E"  /* U+F01E wi-thunderstorm */
#define WI_FOG                  "\xEF\x80\x94"  /* U+F014 wi-fog */
#define WI_WINDY                "\xEF\x80\xA1"  /* U+F021 wi-windy */
#define WI_STRONG_WIND          "\xEF\x81\x90"  /* U+F050 wi-strong-wind */
#define WI_RAINDROPS            "\xEF\x81\x8E"  /* U+F04E wi-raindrops */
#define WI_CLOUD_UP             "\xEF\x81\x80"  /* U+F040 wi-cloud-up (gust) */

/* Metrics / indicators */
#define WI_THERMOMETER          "\xEF\x81\x95"  /* U+F055 wi-thermometer */
#define WI_HUMIDITY             "\xEF\x81\xBA"  /* U+F07A wi-humidity */
#define WI_BAROMETER            "\xEF\x81\xB9"  /* U+F079 wi-barometer */
#define WI_SUNRISE              "\xEF\x81\x91"  /* U+F051 wi-sunrise */
#define WI_SUNSET               "\xEF\x81\x92"  /* U+F052 wi-sunset */
#define WI_WIND_DIRECTION       "\xEF\x82\xB1"  /* U+F0B1 wi-wind-direction */
#define WI_HOT                  "\xEF\x81\xB2"  /* U+F072 wi-hot */
#define WI_EYE                  "\xEF\x81\x87"  /* U+F047 wi-horizon (visibility) */
#define WI_NA                   "\xEF\x81\xBB"  /* U+F07B wi-na (unknown) */
#define WI_SMALL_CRAFT          "\xEF\x83\x8C"  /* U+F0CC wi-small-craft-advisory */

#ifdef __cplusplus
}
#endif
