#!/usr/bin/env python3
"""GUI tool to generate an LVGL 8.x C font file for the speed readout or clock.

Lets the user pick any installed system font, choose a profile (Speed Readout
or Clock), preview it, and generate the C source that gets compiled into the
firmware.
"""

import os
import sys
import tkinter as tk
from tkinter import ttk, messagebox, filedialog
import glob

from PIL import Image, ImageDraw, ImageFont, ImageTk

# ─── defaults ────────────────────────────────────────────────────────
FONT_SIZE = 150
BPP = 4
CHARS = " -.0123456789"
OUTPUT = os.path.join(os.path.dirname(__file__), "..", "src", "lv_font_montserrat_96.c")
FONT_NAME = "lv_font_montserrat_96"

PROFILES = {
    "Speed Readout": {
        "chars": " -.0123456789",
        "output": os.path.join(os.path.dirname(__file__), "..", "src", "lv_font_montserrat_96.c"),
        "font_name": "lv_font_montserrat_96",
        "default_size": 96,
        "preview_text": "65 mph",
    },
    "Speed 150": {
        "chars": " -.0123456789",
        "output": os.path.join(os.path.dirname(__file__), "..", "src", "lv_font_speed_150.c"),
        "font_name": "lv_font_speed_150",
        "default_size": 150,
        "preview_text": "65",
    },
    "Clock": {
        "chars": " -0123456789:AMP",
        "output": os.path.join(os.path.dirname(__file__), "..", "src", "lv_font_clock_96.c"),
        "font_name": "lv_font_clock_96",
        "default_size": 96,
        "preview_text": "12:45 PM",
    },
    "Clock 150": {
        "chars": " -0123456789:AMP",
        "output": os.path.join(os.path.dirname(__file__), "..", "src", "lv_font_clock_150.c"),
        "font_name": "lv_font_clock_150",
        "default_size": 150,
        "preview_text": "12:45",
    },
}


# ─── font rendering ─────────────────────────────────────────────────

def render_glyph(pil_font, ch, ascent):
    """Render one glyph.  Returns (rows, box_w, box_h, ofs_x, ofs_y, adv_w)."""
    adv_w = pil_font.getlength(ch)
    canvas_w = int(adv_w) + 60
    canvas_h = ascent + 60

    img = Image.new("L", (canvas_w, canvas_h), 0)
    draw = ImageDraw.Draw(img)
    draw.text((20, 0), ch, fill=255, font=pil_font)

    pixels = img.load()
    x_min, x_max, y_min, y_max = canvas_w, -1, canvas_h, -1
    for y in range(canvas_h):
        for x in range(canvas_w):
            if pixels[x, y] > 0:
                x_min = min(x_min, x)
                x_max = max(x_max, x)
                y_min = min(y_min, y)
                y_max = max(y_max, y)

    if x_max < 0:
        return [], 0, 0, 0, 0, adv_w

    box_w = x_max - x_min + 1
    box_h = y_max - y_min + 1
    ofs_x = x_min - 20

    baseline_y = ascent
    ofs_y = baseline_y - y_max - 1

    rows = []
    for y in range(y_min, y_max + 1):
        row = []
        for x in range(x_min, x_max + 1):
            row.append(min(15, pixels[x, y] >> 4))
        rows.append(row)

    return rows, box_w, box_h, ofs_x, ofs_y, adv_w


def pack_bitmap_4bpp(rows, box_w):
    # LVGL reads 4bpp bitmaps as a continuous bit stream — no row padding.
    # Flatten all pixels into one stream, then pack two per byte.
    pixels = []
    for row in rows:
        pixels.extend(row)
    data = bytearray()
    for i in range(0, len(pixels), 2):
        hi = pixels[i]
        lo = pixels[i + 1] if i + 1 < len(pixels) else 0
        data.append((hi << 4) | lo)
    return bytes(data)


# ─── C-file generation ──────────────────────────────────────────────

def generate_c_font(ttf_path, font_size, output_path, chars=CHARS,
                    font_name=FONT_NAME, face_index=0):
    pil_font = ImageFont.truetype(ttf_path, font_size, index=face_index)
    ascent, descent = pil_font.getmetrics()
    line_height = ascent + descent

    glyphs = []
    bitmap_data = bytearray()

    sorted_chars = sorted(chars, key=ord)

    for ch in sorted_chars:
        rows, box_w, box_h, ofs_x, ofs_y, adv_w = render_glyph(pil_font, ch, ascent)
        bitmap_index = len(bitmap_data)
        if rows:
            bitmap_data.extend(pack_bitmap_4bpp(rows, box_w))

        glyphs.append({
            "ch": ch,
            "unicode": ord(ch),
            "bitmap_index": bitmap_index,
            "adv_w": int(round(adv_w * 16)),
            "box_w": box_w,
            "box_h": box_h,
            "ofs_x": ofs_x,
            "ofs_y": ofs_y,
        })

    base_line = abs(descent)
    range_start = glyphs[0]["unicode"]
    range_end = glyphs[-1]["unicode"]

    L = []
    L.append("/*******************************************************************************")
    L.append(f" * Size: {font_size} px")
    L.append(f" * Bpp: {BPP}")
    L.append(f" * Font: {os.path.basename(ttf_path)}")
    L.append(f" * Characters: {chars!r}")
    L.append(" * Generated by gen_font_96.py")
    L.append(" ******************************************************************************/")
    L.append("")
    L.append('#include "lvgl.h"')
    L.append("")
    L.append("#ifndef LV_ATTRIBUTE_LARGE_CONST")
    L.append("#define LV_ATTRIBUTE_LARGE_CONST")
    L.append("#endif")
    L.append("")

    # ── bitmap ──
    L.append("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {")
    for i in range(0, len(bitmap_data), 16):
        chunk = bitmap_data[i:i + 16]
        L.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    L.append("};")
    L.append("")

    # ── glyph descriptors ──
    L.append("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
    L.append("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},")
    for g in glyphs:
        ch_repr = repr(g["ch"]) if g["ch"] != " " else "' '"
        L.append(f"    {{.bitmap_index = {g['bitmap_index']}, .adv_w = {g['adv_w']}, "
                 f".box_w = {g['box_w']}, .box_h = {g['box_h']}, "
                 f".ofs_x = {g['ofs_x']}, .ofs_y = {g['ofs_y']}}},  /* U+{g['unicode']:04X} {ch_repr} */")
    L.append("};")
    L.append("")

    # ── unicode list (offsets from range_start) ──
    L.append("static const uint16_t unicode_list_0[] = {")
    offsets = [g["unicode"] - range_start for g in glyphs]
    L.append("    " + ", ".join(f"0x{o:04x}" for o in offsets))
    L.append("};")
    L.append("")

    # ── cmap ── (SPARSE_TINY: unicode_list has offsets, glyph_id = index + glyph_id_start)
    L.append("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
    L.append("    {")
    L.append(f"        .range_start = {range_start},")
    L.append(f"        .range_length = {range_end - range_start + 1},")
    L.append("        .glyph_id_start = 1,")
    L.append("        .unicode_list = unicode_list_0,")
    L.append("        .glyph_id_ofs_list = NULL,")
    L.append(f"        .list_length = {len(glyphs)},")
    L.append("        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY")
    L.append("    }")
    L.append("};")
    L.append("")

    # ── font descriptor ──
    L.append("static lv_font_fmt_txt_dsc_t font_dsc = {")
    L.append("    .glyph_bitmap = glyph_bitmap,")
    L.append("    .glyph_dsc = glyph_dsc,")
    L.append("    .cmaps = cmaps,")
    L.append("    .kern_dsc = NULL,")
    L.append("    .kern_scale = 0,")
    L.append("    .cmap_num = 1,")
    L.append(f"    .bpp = {BPP},")
    L.append("    .kern_classes = 0,")
    L.append("    .bitmap_format = 0,")
    L.append("};")
    L.append("")

    # ── public font struct ──
    L.append(f"const lv_font_t {font_name} = {{")
    L.append("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,")
    L.append("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    L.append(f"    .line_height = {line_height},")
    L.append(f"    .base_line = {base_line},")
    L.append("    .subpx = LV_FONT_SUBPX_NONE,")
    L.append("    .underline_position = -8,")
    L.append("    .underline_thickness = 4,")
    L.append("    .dsc = &font_dsc,")
    L.append("};")
    L.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(L))

    return len(bitmap_data), len(glyphs), line_height, base_line


# ─── GUI ─────────────────────────────────────────────────────────────

class FontGenApp:
    def __init__(self, root):
        self.root = root
        root.title("LVGL Font Generator")
        root.resizable(False, False)

        # Discover system fonts from Windows font directories and registry
        self.font_map = {}  # display name -> file path
        font_dirs = []
        windir = os.environ.get("WINDIR", r"C:\Windows")
        system_fonts_dir = os.path.join(windir, "Fonts")
        font_dirs.append(system_fonts_dir)
        local_fonts = os.path.join(os.environ.get("LOCALAPPDATA", ""), "Microsoft", "Windows", "Fonts")
        if os.path.isdir(local_fonts):
            font_dirs.append(local_fonts)

        # Collect font file paths from directory scanning
        font_files = set()
        for d in font_dirs:
            for ext in ("*.ttf", "*.otf", "*.ttc"):
                for fp in glob.glob(os.path.join(d, ext)):
                    font_files.add(fp)

        # Also read Windows registry for fonts not in standard directories
        try:
            import winreg
            reg_key = winreg.OpenKey(
                winreg.HKEY_LOCAL_MACHINE,
                r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts")
            i = 0
            while True:
                try:
                    _name, value, _type = winreg.EnumValue(reg_key, i)
                    i += 1
                    if not value:
                        continue
                    # Registry values may be just filenames (relative to Fonts dir) or full paths
                    if os.path.isabs(value):
                        fp = value
                    else:
                        fp = os.path.join(system_fonts_dir, value)
                    if os.path.isfile(fp):
                        font_files.add(fp)
                except OSError:
                    break
            winreg.CloseKey(reg_key)
        except Exception:
            pass

        # Load each font file, handling .ttc collections with multiple face indices
        for fp in font_files:
            lower = fp.lower()
            if lower.endswith(".ttc"):
                # TrueType Collection — try face indices until we run out
                for idx in range(20):
                    try:
                        f = ImageFont.truetype(fp, 20, index=idx)
                        name = f.getname()
                        display = f"{name[0]} ({name[1]})"
                        self.font_map[display] = (fp, idx)
                    except Exception:
                        break
            else:
                try:
                    f = ImageFont.truetype(fp, 20)
                    name = f.getname()
                    display = f"{name[0]} ({name[1]})"
                    self.font_map[display] = (fp, 0)
                except Exception:
                    pass

        # Also add bundled Montserrat
        mont_path = os.path.join(
            os.path.dirname(__file__), "..",
            ".pio", "libdeps", "waveshare_esp32s3_touch_amoled_1_8",
            "lvgl", "scripts", "built_in_font", "Montserrat-Medium.ttf")
        if os.path.isfile(mont_path):
            self.font_map["Montserrat Medium (LVGL bundled)"] = (mont_path, 0)

        self.font_names = sorted(self.font_map.keys(), key=str.lower)

        # ── Font selector ──
        frame = ttk.LabelFrame(root, text="Font", padding=10)
        frame.pack(padx=10, pady=(10, 5), fill="x")

        ttk.Label(frame, text="Font:").grid(row=0, column=0, sticky="w")
        self.font_var = tk.StringVar()
        self.font_combo = ttk.Combobox(frame, textvariable=self.font_var,
                                       values=self.font_names, width=50, state="readonly")
        self.font_combo.grid(row=0, column=1, padx=5)
        # Default to Montserrat if available
        for n in self.font_names:
            if "montserrat" in n.lower() and "bundled" in n.lower():
                self.font_var.set(n)
                break

        ttk.Label(frame, text="Size (px):").grid(row=1, column=0, sticky="w", pady=(5, 0))
        self.size_var = tk.IntVar(value=96)
        self.size_spin = ttk.Spinbox(frame, from_=48, to=200, textvariable=self.size_var, width=6)
        self.size_spin.grid(row=1, column=1, sticky="w", padx=5, pady=(5, 0))

        ttk.Label(frame, text="Profile:").grid(row=2, column=0, sticky="w", pady=(5, 0))
        self.profile_var = tk.StringVar(value="Speed Readout")
        self.profile_combo = ttk.Combobox(frame, textvariable=self.profile_var,
                                           values=list(PROFILES.keys()), width=20, state="readonly")
        self.profile_combo.grid(row=2, column=1, sticky="w", padx=5, pady=(5, 0))
        self.profile_combo.bind("<<ComboboxSelected>>", self._on_profile_change)

        # ── Browse for TTF ──
        ttk.Button(frame, text="Browse TTF...", command=self._browse).grid(
            row=0, column=2, padx=5)

        # ── Preview ──
        preview_frame = ttk.LabelFrame(root, text="Preview", padding=10)
        preview_frame.pack(padx=10, pady=5, fill="x")

        self.preview_canvas = tk.Canvas(preview_frame, width=360, height=120, bg="black")
        self.preview_canvas.pack()

        ttk.Button(preview_frame, text="Refresh Preview", command=self._preview).pack(pady=(5, 0))

        # ── Generate ──
        btn_frame = ttk.Frame(root, padding=10)
        btn_frame.pack(fill="x")

        self.status_var = tk.StringVar(value="Select a font and click Generate.")
        ttk.Label(btn_frame, textvariable=self.status_var, wraplength=400).pack(side="left", fill="x", expand=True)
        ttk.Button(btn_frame, text="Generate", command=self._generate).pack(side="right")

        self._preview()

    def _on_profile_change(self, event=None):
        p = PROFILES.get(self.profile_var.get())
        if p:
            self.size_var.set(p["default_size"])
            self._preview()

    def _browse(self):
        path = filedialog.askopenfilename(
            filetypes=[("TrueType / OpenType", "*.ttf *.otf *.ttc"), ("All files", "*.*")])
        if path:
            try:
                f = ImageFont.truetype(path, 20)
                name = f.getname()
                display = f"{name[0]} ({name[1]}) [custom]"
                self.font_map[display] = (path, 0)
                self.font_names = sorted(self.font_map.keys(), key=str.lower)
                self.font_combo["values"] = self.font_names
                self.font_var.set(display)
                self._preview()
            except Exception as e:
                messagebox.showerror("Error", f"Cannot load font:\n{e}")

    def _get_font_info(self):
        """Return (path, index) tuple or None."""
        name = self.font_var.get()
        return self.font_map.get(name)

    def _preview(self):
        self.preview_canvas.delete("all")
        info = self._get_font_info()
        if not info:
            return
        try:
            path, idx = info
            size = self.size_var.get()
            pil_font = ImageFont.truetype(path, size, index=idx)
            ascent, descent = pil_font.getmetrics()
            canvas_h = ascent + descent + 20
            canvas_w = 500
            img = Image.new("L", (canvas_w, canvas_h), 0)
            draw = ImageDraw.Draw(img)
            prof = PROFILES.get(self.profile_var.get(), PROFILES["Speed Readout"])
            draw.text((10, 10), prof["preview_text"], fill=255, font=pil_font)
            self.preview_canvas.config(width=canvas_w, height=canvas_h)
            self._preview_img = ImageTk.PhotoImage(img)
            self.preview_canvas.create_image(0, 0, anchor="nw", image=self._preview_img)
        except Exception as e:
            self.preview_canvas.create_text(180, 60, text=str(e), fill="red")

    def _generate(self):
        info = self._get_font_info()
        if not info:
            messagebox.showwarning("No font", "Please select a font first.")
            return
        path, idx = info
        size = self.size_var.get()
        prof = PROFILES[self.profile_var.get()]
        output = prof["output"]
        self.status_var.set("Generating...")
        self.root.update()
        try:
            bmp_size, n_glyphs, lh, bl = generate_c_font(
                path, size, output,
                chars=prof["chars"], font_name=prof["font_name"],
                face_index=idx)
            self.status_var.set(
                f"Done!  {n_glyphs} glyphs, {bmp_size:,} bytes bitmap, "
                f"line_height={lh}, base_line={bl}\n"
                f"Saved to {output}")
            messagebox.showinfo("Success",
                                f"Font generated successfully!\n\n"
                                f"{n_glyphs} glyphs, {bmp_size:,} bytes\n"
                                f"Output: {output}\n\n"
                                f"Rebuild firmware to use the new font.")
        except Exception as e:
            self.status_var.set(f"Error: {e}")
            messagebox.showerror("Error", str(e))


def main():
    # If run with --no-gui, generate using bundled Montserrat (for CI/scripts)
    if "--no-gui" in sys.argv:
        mont_path = os.path.join(
            os.path.dirname(__file__), "..",
            ".pio", "libdeps", "waveshare_esp32s3_touch_amoled_1_8",
            "lvgl", "scripts", "built_in_font", "Montserrat-Medium.ttf")

        # Determine profile from --profile argument
        profile_name = "Speed Readout"
        for i, arg in enumerate(sys.argv):
            if arg == "--profile" and i + 1 < len(sys.argv):
                profile_name = sys.argv[i + 1]
                break

        if profile_name not in PROFILES:
            print(f"Unknown profile: {profile_name}")
            print(f"Available profiles: {', '.join(PROFILES.keys())}")
            sys.exit(1)

        prof = PROFILES[profile_name]
        font_size = prof["default_size"]
        output = prof["output"]

        bmp_size, n_glyphs, lh, bl = generate_c_font(
            mont_path, font_size, output,
            chars=prof["chars"], font_name=prof["font_name"])
        print(f"Generated {output} ({profile_name})")
        print(f"  {n_glyphs} glyphs, {bmp_size:,} bytes, line_height={lh}, base_line={bl}")
        return

    root = tk.Tk()
    FontGenApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()
