#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# gen_weather_font.sh
#
# Rebuilds the LVGL font sources used by the weather and idle screens.
#
# lmarzen/esp32-weather-epd ships fixed-size 1-bit bitmap headers generated
# from the same Erik Flowers Weather Icons artwork. For this LCD UI we keep
# that fixed-size idea, but generate antialiased LVGL fonts so icons and
# temperature text can be colored by LVGL and rendered at native resolution.
#
# Outputs:
#   src/controller/ui/fonts/weather_icons_28.c
#   src/controller/ui/fonts/weather_icons_60.c
#   src/controller/ui/fonts/weather_icons_96.c
#   src/controller/ui/fonts/weather_icons_120.c
#   src/controller/ui/fonts/weather_digits_72.c
#   src/controller/ui/fonts/weather_digits_96.c
#   src/controller/ui/fonts/weather_digits_150.c
#   src/controller/ui/fonts/weather_icons.h
#
# Requirements:
#   * curl
#   * node + npm (lv_font_conv is installed in a user cache)
#
# Source fonts:
#   * Erik Flowers Weather Icons, SIL OFL 1.1
#     https://github.com/erikflowers/weather-icons
#   * Barlow Condensed SemiBold, SIL OFL 1.1
#     https://github.com/google/fonts/tree/main/ofl/barlowcondensed
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$REPO_ROOT/src/controller/ui/fonts"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/p4-walldisplay-fontgen"
NODE_DIR="$CACHE_DIR/node"
ASSET_DIR="$CACHE_DIR/assets"

LV_FONT_CONV_VERSION="1.5.2"
WEATHER_TTF_URL="https://raw.githubusercontent.com/erikflowers/weather-icons/master/font/weathericons-regular-webfont.ttf"
DIGITS_TTF_URL="https://raw.githubusercontent.com/google/fonts/main/ofl/barlowcondensed/BarlowCondensed-SemiBold.ttf"

WEATHER_TTF="$ASSET_DIR/weathericons-regular-webfont.ttf"
DIGITS_TTF="$ASSET_DIR/BarlowCondensed-SemiBold.ttf"
CONVERTER="$NODE_DIR/node_modules/.bin/lv_font_conv"

WEATHER_ICON_SIZES=(28 60 96 120)
DIGIT_SIZES=(72 96 150)

# Glyphs referenced by weather_icons.h. These are Weather Icons PUA values.
WEATHER_RANGES="\
0xF002,0xF003,0xF008,0xF00A,0xF00D,0xF010,\
0xF014,0xF019,0xF01B,0xF01E,0xF021,0xF028,0xF02A,0xF02D,\
0xF02E,0xF040,0xF041,0xF047,0xF04A,0xF04E,0xF050,0xF051,\
0xF052,0xF055,0xF056,0xF072,0xF079,0xF07A,0xF07B,0xF086,\
0xF0B1,0xF0CC"

# Temperature/clock subset: '-', '.', '/', digits, ':', space, degree sign.
DIGIT_RANGES="0x20,0x2D-0x3A,0x00B0"

need_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "error: missing required command: $1" >&2
        exit 1
    fi
}

download_if_missing() {
    local url="$1"
    local out="$2"
    if [[ -s "$out" ]]; then
        return
    fi
    echo "==> downloading $(basename "$out")"
    local tmp="$out.tmp"
    curl -fsSL "$url" -o "$tmp"
    mv "$tmp" "$out"
}

ensure_converter() {
    if [[ -x "$CONVERTER" ]]; then
        return
    fi
    echo "==> installing lv_font_conv@$LV_FONT_CONV_VERSION in $NODE_DIR"
    mkdir -p "$NODE_DIR"
    (
        cd "$NODE_DIR"
        npm init -y >/dev/null
        npm install --silent --no-audit --no-fund "lv_font_conv@$LV_FONT_CONV_VERSION"
    )
}

generate_font() {
    local source_ttf="$1"
    local ranges="$2"
    local size="$3"
    local out="$4"
    echo "==> generating ${out#$REPO_ROOT/} (${size}px)"
    "$CONVERTER" \
        --bpp 4 \
        --size "$size" \
        --font "$source_ttf" \
        -r "$ranges" \
        --format lvgl \
        --force-fast-kern-format \
        --no-compress \
        --no-prefilter \
        --lv-include "lvgl.h" \
        -o "$out"
    if command -v perl >/dev/null 2>&1; then
        FONTGEN_REPO_ROOT="$REPO_ROOT" FONTGEN_CACHE_DIR="$CACHE_DIR" \
            perl -0pi -e 's#\Q$ENV{FONTGEN_REPO_ROOT}\E/##g; s#\Q$ENV{FONTGEN_CACHE_DIR}\E#<font-cache>#g' "$out"
    fi
}

write_header() {
    local out="$OUT_DIR/weather_icons.h"
    echo "==> writing ${out#$REPO_ROOT/}"
    cat > "$out" <<'HEADER_EOF'
/* ---------------------------------------------------------------------------
 * weather_icons.h - generated LVGL weather icon and numeric font declarations.
 *
 * Generated by scripts/gen_weather_font.sh. UTF-8 string literals below encode
 * the Private-Use-Area code-points from Erik Flowers Weather Icons.
 *
 * lmarzen/esp32-weather-epd gets its reference look from fixed-size bitmaps
 * under platformio/lib/esp32-weather-epd-assets/icons and maps OWM conditions
 * through display_utils.cpp:getConditionsBitmap(). This firmware uses the same
 * icon vocabulary as native-size LVGL fonts instead of copying GPL bitmap
 * headers into the project.
 * --------------------------------------------------------------------------- */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(weather_icons_28);
LV_FONT_DECLARE(weather_icons_60);
LV_FONT_DECLARE(weather_icons_96);
LV_FONT_DECLARE(weather_icons_120);
LV_FONT_DECLARE(weather_digits_72);
LV_FONT_DECLARE(weather_digits_96);
LV_FONT_DECLARE(weather_digits_150);

/* Day variants */
#define WI_DAY_SUNNY            "\xEF\x80\x8D"  /* U+F00D wi-day-sunny */
#define WI_DAY_CLOUDY           "\xEF\x80\x82"  /* U+F002 wi-day-cloudy */
#define WI_DAY_RAIN             "\xEF\x80\x88"  /* U+F008 wi-day-rain */
#define WI_DAY_SNOW             "\xEF\x80\x8A"  /* U+F00A wi-day-snow */
#define WI_DAY_THUNDER          "\xEF\x80\x90"  /* U+F010 wi-day-thunderstorm */
#define WI_DAY_FOG              "\xEF\x80\x83"  /* U+F003 wi-day-fog */

/* Night variants */
#define WI_NIGHT_CLEAR          "\xEF\x80\xAE"  /* U+F02E wi-night-clear */
#define WI_NIGHT_CLOUDY         "\xEF\x82\x86"  /* U+F086 wi-night-alt-cloudy */
#define WI_NIGHT_RAIN           "\xEF\x80\xA8"  /* U+F028 wi-night-alt-rain */
#define WI_NIGHT_SNOW           "\xEF\x80\xAA"  /* U+F02A wi-night-alt-snow */
#define WI_NIGHT_THUNDER        "\xEF\x80\xAD"  /* U+F02D wi-night-alt-thunderstorm */
#define WI_NIGHT_FOG            "\xEF\x81\x8A"  /* U+F04A wi-night-fog */

/* Generic */
#define WI_CLOUD                "\xEF\x81\x81"  /* U+F041 wi-cloud */
#define WI_RAIN                 "\xEF\x80\x99"  /* U+F019 wi-rain */
#define WI_SNOW                 "\xEF\x80\x9B"  /* U+F01B wi-snow */
#define WI_TORNADO              "\xEF\x81\x96"  /* U+F056 wi-tornado */
#define WI_THUNDER              "\xEF\x80\x9E"  /* U+F01E wi-thunderstorm */
#define WI_FOG                  "\xEF\x80\x94"  /* U+F014 wi-fog */
#define WI_WINDY                "\xEF\x80\xA1"  /* U+F021 wi-windy */
#define WI_STRONG_WIND          "\xEF\x81\x90"  /* U+F050 wi-strong-wind */
#define WI_RAINDROPS            "\xEF\x81\x8E"  /* U+F04E wi-raindrops */
#define WI_CLOUD_UP             "\xEF\x81\x80"  /* U+F040 wi-cloud-up (gust) */

/* Metrics / indicators */
#define WI_THERMOMETER          "\xEF\x81\x95"  /* U+F055 wi-thermometer */
#define WI_HUMIDITY             "\xEF\x81\xBA"  /* U+F07A wi-humidity */
#define WI_BAROMETER            "\xEF\x81\xB9"  /* U+F079 wi-barometer */
#define WI_SUNRISE              "\xEF\x81\x91"  /* U+F051 wi-sunrise */
#define WI_SUNSET               "\xEF\x81\x92"  /* U+F052 wi-sunset */
#define WI_WIND_DIRECTION       "\xEF\x82\xB1"  /* U+F0B1 wi-wind-direction */
#define WI_HOT                  "\xEF\x81\xB2"  /* U+F072 wi-hot */
#define WI_EYE                  "\xEF\x81\x87"  /* U+F047 wi-horizon (visibility) */
#define WI_NA                   "\xEF\x81\xBB"  /* U+F07B wi-na (unknown) */
#define WI_SMALL_CRAFT          "\xEF\x83\x8C"  /* U+F0CC wi-small-craft-advisory */

#ifdef __cplusplus
}
#endif
HEADER_EOF
}

main() {
    need_cmd curl
    need_cmd node
    need_cmd npm

    mkdir -p "$OUT_DIR" "$ASSET_DIR"
    download_if_missing "$WEATHER_TTF_URL" "$WEATHER_TTF"
    download_if_missing "$DIGITS_TTF_URL" "$DIGITS_TTF"
    ensure_converter

    for size in "${WEATHER_ICON_SIZES[@]}"; do
        generate_font "$WEATHER_TTF" "$WEATHER_RANGES" "$size" \
            "$OUT_DIR/weather_icons_${size}.c"
    done

    for size in "${DIGIT_SIZES[@]}"; do
        generate_font "$DIGITS_TTF" "$DIGIT_RANGES" "$size" \
            "$OUT_DIR/weather_digits_${size}.c"
    done

    write_header
    echo "==> done"
}

main "$@"
