#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# gen_ui_icons_font.sh
#
# Rebuilds the shared LVGL icon font used across the UI chrome: the bottom
# navigation bar (nav_bar.c), the Settings category menu, and the status bar.
#
# Mirrors gen_weather_font.sh: download an icon TTF, then use lv_font_conv to
# emit antialiased LVGL fonts containing only the glyphs the UI needs, so they
# recolor with LVGL (active/inactive/status states) like any other glyph.
#
# Three sizes are emitted because LVGL bitmap fonts do not scale: the status
# bar renders at 24px, the Settings menu at 28px, and the nav bar at 32px.
#
# Outputs:
#   src/controller/ui/fonts/ui_icons_24.c
#   src/controller/ui/fonts/ui_icons_28.c
#   src/controller/ui/fonts/ui_icons_32.c
#   src/controller/ui/fonts/ui_icons.h
#
# Requirements:
#   * curl
#   * node + npm (lv_font_conv is installed in a user cache)
#
# Source font:
#   * Phosphor Icons (regular), MIT License
#     https://github.com/phosphor-icons/web
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$REPO_ROOT/src/controller/ui/fonts"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/p4-walldisplay-fontgen"
NODE_DIR="$CACHE_DIR/node"
ASSET_DIR="$CACHE_DIR/assets"

LV_FONT_CONV_VERSION="1.5.2"
PHOSPHOR_TTF_URL="https://raw.githubusercontent.com/phosphor-icons/web/master/src/regular/Phosphor.ttf"
PHOSPHOR_BOLD_TTF_URL="https://raw.githubusercontent.com/phosphor-icons/web/master/src/bold/Phosphor-Bold.ttf"
PHOSPHOR_TTF="$ASSET_DIR/Phosphor.ttf"
PHOSPHOR_BOLD_TTF="$ASSET_DIR/Phosphor-Bold.ttf"
CONVERTER="$NODE_DIR/node_modules/.bin/lv_font_conv"

# Regular-weight sizes: status bar formerly 24, Settings menu 28, nav bar 32.
# (The status bar now uses the bold 30px font below for a heavier, larger look.)
UI_ICON_SIZES=(24 28 32)
# Bold weight, status-bar only — bigger + thicker than the regular glyphs.
UI_ICON_BOLD_SIZES=(30)

# Phosphor PUA code-points referenced by ui_icons.h. Keep in sync with the
# UI_ICON_* defines in write_header below. Phosphor weights share codepoints,
# so the same ranges feed both the regular and bold fonts.
#   lights/bulb E2DC, weather/cloud-sun E540, weather-off/cloud-slash E1B6,
#   timer/hourglass E2B2, gear E270, wifi-high E4EA, wifi-low E4EC,
#   wifi-slash E4F2, monitor E32E, moon E330, image E2CA, floppy E248,
#   lightning E2DE, lightning-slash E2E0, link E2E2, link-break E2E4,
#   microphone E326, microphone-slash E328, info E2CE, sun E472, sun-dim E474
UI_RANGES="0xE1B6,0xE248,0xE270,0xE2B2,0xE2CA,0xE2CE,0xE2DC,0xE2DE,0xE2E0,0xE2E2,0xE2E4,0xE326,0xE328,0xE32E,0xE330,0xE472,0xE474,0xE4EA,0xE4EC,0xE4F2,0xE540"

need_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "error: missing required command: $1" >&2
        exit 1
    fi
}

download_if_missing() {
    local url="$1"
    local out="$2"
    if [[ -s "$out" ]]; then
        return
    fi
    echo "==> downloading $(basename "$out")"
    local tmp="$out.tmp"
    curl -fsSL "$url" -o "$tmp"
    mv "$tmp" "$out"
}

ensure_converter() {
    if [[ -x "$CONVERTER" ]]; then
        return
    fi
    echo "==> installing lv_font_conv@$LV_FONT_CONV_VERSION in $NODE_DIR"
    mkdir -p "$NODE_DIR"
    (
        cd "$NODE_DIR"
        npm init -y >/dev/null
        npm install --silent --no-audit --no-fund "lv_font_conv@$LV_FONT_CONV_VERSION"
    )
}

generate_font() {
    local source_ttf="$1"
    local ranges="$2"
    local size="$3"
    local out="$4"
    echo "==> generating ${out#$REPO_ROOT/} (${size}px)"
    "$CONVERTER" \
        --bpp 4 \
        --size "$size" \
        --font "$source_ttf" \
        -r "$ranges" \
        --format lvgl \
        --force-fast-kern-format \
        --no-compress \
        --no-prefilter \
        --lv-include "lvgl.h" \
        -o "$out"
    if command -v perl >/dev/null 2>&1; then
        FONTGEN_REPO_ROOT="$REPO_ROOT" FONTGEN_CACHE_DIR="$CACHE_DIR" \
            perl -0pi -e 's#\Q$ENV{FONTGEN_REPO_ROOT}\E/##g; s#\Q$ENV{FONTGEN_CACHE_DIR}\E#<font-cache>#g' "$out"
    fi
}

write_header() {
    local out="$OUT_DIR/ui_icons.h"
    echo "==> writing ${out#$REPO_ROOT/}"
    cat > "$out" <<'HEADER_EOF'
/* ---------------------------------------------------------------------------
 * ui_icons.h - generated shared LVGL icon font for UI chrome (nav bar,
 * Settings menu, status bar).
 *
 * Generated by scripts/gen_ui_icons_font.sh from Phosphor Icons (MIT). The
 * UTF-8 string literals encode Phosphor Private-Use-Area code-points; rendered
 * with ui_icons_24/28/32 they recolor with LVGL like any other glyph.
 * --------------------------------------------------------------------------- */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(ui_icons_24);
LV_FONT_DECLARE(ui_icons_28);
LV_FONT_DECLARE(ui_icons_32);
LV_FONT_DECLARE(ui_icons_bold_30);

#define UI_ICON_LIGHTS      "\xEE\x8B\x9C"  /* U+E2DC ph-lightbulb */
#define UI_ICON_WEATHER     "\xEE\x95\x80"  /* U+E540 ph-cloud-sun */
#define UI_ICON_WEATHER_OFF "\xEE\x86\xB6"  /* U+E1B6 ph-cloud-slash */
#define UI_ICON_TIMER       "\xEE\x8A\xB2"  /* U+E2B2 ph-hourglass */
#define UI_ICON_SETTINGS    "\xEE\x89\xB0"  /* U+E270 ph-gear */
#define UI_ICON_WIFI        "\xEE\x93\xAA"  /* U+E4EA ph-wifi-high */
#define UI_ICON_WIFI_LOW    "\xEE\x93\xAC"  /* U+E4EC ph-wifi-low */
#define UI_ICON_WIFI_OFF    "\xEE\x93\xB2"  /* U+E4F2 ph-wifi-slash */
#define UI_ICON_DISPLAY     "\xEE\x8C\xAE"  /* U+E32E ph-monitor */
#define UI_ICON_IDLE        "\xEE\x8C\xB0"  /* U+E330 ph-moon */
#define UI_ICON_THEME       "\xEE\x8B\x8A"  /* U+E2CA ph-image */
#define UI_ICON_SD          "\xEE\x89\x88"  /* U+E248 ph-floppy-disk */
#define UI_ICON_WLED        "\xEE\x8B\x9E"  /* U+E2DE ph-lightning */
#define UI_ICON_WLED_OFF    "\xEE\x8B\xA0"  /* U+E2E0 ph-lightning-slash */
#define UI_ICON_LINK        "\xEE\x8B\xA2"  /* U+E2E2 ph-link */
#define UI_ICON_LINK_OFF    "\xEE\x8B\xA4"  /* U+E2E4 ph-link-break */
#define UI_ICON_AUDIO       "\xEE\x8C\xA6"  /* U+E326 ph-microphone */
#define UI_ICON_AUDIO_OFF   "\xEE\x8C\xA8"  /* U+E328 ph-microphone-slash */
#define UI_ICON_INFO        "\xEE\x8B\x8E"  /* U+E2CE ph-info */
#define UI_ICON_SUN         "\xEE\x91\xB2"  /* U+E472 ph-sun */
#define UI_ICON_SUN_DIM     "\xEE\x91\xB4"  /* U+E474 ph-sun-dim */

#ifdef __cplusplus
}
#endif
HEADER_EOF
}

main() {
    need_cmd curl
    need_cmd node
    need_cmd npm

    mkdir -p "$OUT_DIR" "$ASSET_DIR"
    download_if_missing "$PHOSPHOR_TTF_URL" "$PHOSPHOR_TTF"
    download_if_missing "$PHOSPHOR_BOLD_TTF_URL" "$PHOSPHOR_BOLD_TTF"
    ensure_converter

    for size in "${UI_ICON_SIZES[@]}"; do
        generate_font "$PHOSPHOR_TTF" "$UI_RANGES" "$size" \
            "$OUT_DIR/ui_icons_${size}.c"
    done

    for size in "${UI_ICON_BOLD_SIZES[@]}"; do
        generate_font "$PHOSPHOR_BOLD_TTF" "$UI_RANGES" "$size" \
            "$OUT_DIR/ui_icons_bold_${size}.c"
    done

    write_header
    echo "==> done"
}

main "$@"
